version: "3.5"
   
services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin
    environment:
      - P2G_PELOTON_EMAIL=peloton@gmail.com
      - P2G_PELOTON_PASS=peloton_password
      - P2G_GARMIN_ENABLE_UPLOAD=true
      - P2G_GARMIN_EMAIL=garmin@gmail.com
      - P2G_GARMIN_PASS=garmin_password
      - P2G_NUM=4
      - PTG_POLLING_INTERVAL_SECONDS=3600 # 1hr
      # additional environment vars can be configured here
    volumes:
      - ./logs:/logs
      - ./output:/output
